### ISSUE TITLE
Scons can't seem to find v142!!!

### ISSUE THREAD

**Issue by halohsu** [SConsProject/scons#4182]
**Describe the bug**

SCons can't seem to find v142!!!
When I was compiling MongoDB source code:

```
E:\mongodb-src-r5.0.9>python buildscripts/scons.py install-mongod --disable-warnings-as-errors
Checking required python packages...
Requirements list:
    Cheetah3<=3.2.6.post1
    PyYAML<=6.0.0,>=3.0.0
    oauthlib==3.1.1
    pkce==1.0.3
    psutil<=5.8.0
    pymongo<4.0,>=3.9
    pypiwin32==223; sys_platform == "win32" and python_version > "3"
    pywin32==304; sys_platform == "win32" and python_version > "3"
    regex<=2021.11.10
    requests-oauthlib==1.3.0
    requests<=2.26.0,>=2.0.0
    requirements_parser<=0.3.1
    setuptools
Resolved to these distributions:
    certifi 2022.6.15
    charset-normalizer 2.0.12
    cheetah3 3.2.6.post1
    idna 3.3
    oauthlib 3.1.1
    pkce 1.0.3
    psutil 5.8.0
    pymongo 3.12.3
    pypiwin32 223
    pywin32 304
    pyyaml 6.0
    regex 2021.11.10
    requests 2.26.0
    requests-oauthlib 1.3.0
    requirements-parser 0.3.1
    setuptools 58.1.0
    types-setuptools 57.4.18
    urllib3 1.26.9
scons: Reading SConscript files ...
scons: running with args C:\Program Files\Python3\python.exe buildscripts/scons.py install-mongod --disable-warnings-as-errors
scons version: 3.1.2
python version: 3 10 5 'final' 0

scons: warning: VC version 14.2 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: []
File "E:\mongodb-src-r5.0.9\SConstruct", line 1204, in <module>

scons: warning: VC version 14.2 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: []
File "E:\mongodb-src-r5.0.9\SConstruct", line 1204, in <module>

scons: warning: VC version 14.2 not installed.  C/C++ compilers are most likely not set correctly.
 Installed versions are: []
File "E:\mongodb-src-r5.0.9\SConstruct", line 1204, in <module>
CC is cl
cl found in $PATH at C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE
C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE resolves to C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.exe
CXX is $CC
$CC was not found in $PATH
$CC resolves to E:\mongodb-src-r5.0.9\$CC
Checking if C++ compiler "$CC" is MSVC... no
Checking if C++ compiler "$CC" is clang... no
Checking if C++ compiler "$CC" is GCC... no
Couldn't identify the C++ compiler
See E:\mongodb-src-r5.0.9\build\scons\config.log for details
```

**Required information**
* Version of SCons: 

```
E:\mongodb-src-r5.0.9>scons -v
SCons by Steven Knight et al.:
        SCons: v4.3.0.559790274f66fa55251f5754de34820a29c7327a, Tue, 16 Nov 2021 19:09:21 +0000, by bdeegan on octodog
        SCons path: ['C:\\Program Files\\Python3\\lib\\site-packages\\SCons']
Copyright (c) 2001 - 2021 The SCons Foundation
```

* Version of Python

```
E:\mongodb-src-r5.0.9>python -V
Python 3.10.5
```

* Which python distribution if applicable: www.python.org
* How you installed SCons: `pip install scons`
* What Platform are you on: Windows 11
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues:
    *  Download the mongodb source code from offical website.
    *  Download and install VistualStudio 2022 from Microsoft.
    *  Double click VistualStudio Installer: C++ Desktop Dev, C++ Game Dev, v142, v143
    *  Download and install Python3.10 from www.python.org
    *  Into to the mongodb source code dir.
    *  Exec: `python -m pip install -r etc/pip/compile-requirements.txt`
    *  Exec: `python buildscripts/scons.py install-mongod --disable-warnings-as-errors`

**Comment by bdbaddog** [comment]
Please set the shell variable SCONS_MSCOMMON_DEBUG to point to a file and attach that file to this issue.

**Comment by bdbaddog** [comment]
Firstly: your command line
`python buildscripts/scons.py`
Is not running your installed scons.
You're running the vendored version of scons in the mongodb source tree.
(Which depending on which version of mongodb source code could be fairly old)

Try running real scons 
`scons install-mongod --disable-warnings-as-errors`

And let us know if that works.

If that doesn't work. 
There's current a PR in flight for improving MSVC detection and selection.

If you're able pull this code:
git@github.com:jcbrill/scons.git
And then checkout branch: jbrill-msvc-batchargs

Then you can run it via
`<path where you checked the above out>/scripts/scons.py install-mongod --disable-warnings-as-errors`

**Comment by jcbrill** [comment]
> How to reproduce your issue? Please include a small self contained reproducer. Likely a SConstruct should do for most issues:
Download the mongodb source code from offical website.
Download and install VistualStudio 2022 from Microsoft.
Double click VistualStudio Installer: C++ Desktop Dev, C++ Game Dev, v142, v143
Download and install Python3.10 from [www.python.org](http://www.python.org/)
Into to the mongodb source code dir.
Exec: python -m pip install -r etc/pip/compile-requirements.txt
Exec: python buildscripts/scons.py install-mongod --disable-warnings-as-errors

The v142 toolset will not be found via VS2022 (v143).  Same as #3664.

**Comment by bdbaddog** [comment]
> > How to reproduce your issue? Please include a small self contained reproducer. Likely a SConstruct should do for most issues:
> > Download the mongodb source code from offical website.
> > Download and install VistualStudio 2022 from Microsoft.
> > Double click VistualStudio Installer: C++ Desktop Dev, C++ Game Dev, v142, v143
> > Download and install Python3.10 from [www.python.org](http://www.python.org/)
> > Into to the mongodb source code dir.
> > Exec: python -m pip install -r etc/pip/compile-requirements.txt
> > Exec: python buildscripts/scons.py install-mongod --disable-warnings-as-errors
> 
> The v142 toolset will not be found via VS2022 (v143).

So this is known issue, resolved by your PR?
(was thinking that's the case)

@bluemiaomiao - any reason to not use v143? That should work (right @jcbrill ?)

**Comment by jcbrill** [comment]
> So this is known issue, resolved by your PR?
(was thinking that's the case)

Since the new PR is applied after selection of msvc installation, it would have to be one of:
```
Environment(MSVC_VERSION='14.3', MSVC_TOOLSET_VERSION='14.2')
Environment(MSVC_TOOLSET_VERSION='14.2')
```
>any reason to not use v143? That should work (right @jcbrill ?)

Based on the above, it looks like '14.2' might be hard-coded somewhere.   It appears to be a '14.2' MSVC_VERSION request .  Changing to '14.3' wherever necessary should work.

**Comment by halohsu** [comment]
> Firstly: your command line `python buildscripts/scons.py` Is not running your installed scons. You're running the vendored version of scons in the mongodb source tree. (Which depending on which version of mongodb source code could be fairly old)
> 
> Try running real scons `scons install-mongod --disable-warnings-as-errors`
> 
> And let us know if that works.
> 
> If that doesn't work. There's current a PR in flight for improving MSVC detection and selection.
> 
> If you're able pull this code: [git@github.com](mailto:git@github.com):jcbrill/scons.git And then checkout branch: jbrill-msvc-batchargs
> 
> Then you can run it via `<path where you checked the above out>/scripts/scons.py install-mongod --disable-warnings-as-errors`

Before the errors, Scons has been installed. But the problem remains.

**Comment by halohsu** [comment]
> 

Neither you nor I can ask any project to upgrade to the latest msvc compiler in time. In fact, we must admit that the ecology and compatibility of C++ compiler and building tools are vert poor. Let Rust finish this.

**Comment by bdbaddog** [comment]
@bluemiaomiao - @dmoody256 who is a frequent contributor to the project said mongoDB should build fine with MSVC2022 (v143), assuming you are on a fairly new release.


I'm not sure you understood what I said about running `python buildscripts/scons.py` that does not install the scons you installed via pip. it runs a local copy of scons which is in the mongodb source tree.

So if you run with scons (assuming it's in your path from your pip install), you'll get the actual scons 4.3.0.

Have you tried that?

**Comment by halohsu** [comment]
> 

Yes

**Comment by dmoody256** [comment]
@bluemiaomiao the mongodb build does not support using Visual Studio 2022 with the 14.2 toolset. The local in-tree scons is 3.1.2 and has a small patch to allow Visual Studio 2022 with the default 14.3 toolset. You must either install Visual Studio 2019 which uses default toolset 14.2 or you must install Visual Studio 2022 with default toolset 14.3.

@jcbrill has a PR https://github.com/SCons/scons/pull/4174 which gives a new option to select alternate toolsets for a given Visual Studio installation.

**Comment by jcbrill** [comment]
I fear this is going to come up frequently.  This issue is a duplicate of #3664 (i.e., same root cause).

As implemented, PR #4174 does not affect the selection of MSVC.  The toolset version is applied after msvc is selected which may be the default version of msvc if MSVC_VERSION is not specified.

The ***default*** MSVC_VERSION for mongdb v5.0.9-51 is hard-coded as "14.2".  It may be worth trying 14.3 first:
```
scons install-mongod --disable-warnings-as-errors MSVC_VERSION=14.3
```

As an example for compiling mongdb v5.0.9-51 with VS2022 (14.3) and the 14.2 toolset using PR #4174, ***MSVC_TOOLSET_VERSION was added to the mongodb SConstruct after MSVC_VERSION***:
```
env_vars.Add('MSVC_VERSION',
    help='Sets the version of Visual C++ to use (e.g. 14.1 for VS2017, 14.2 for VS2019)',
    default="14.2")

env_vars.Add('MSVC_TOOLSET_VERSION',
    help='Sets the toolset version of Visual C++ to use (e.g. 14.1 for VS2017, 14.2 for VS2019)')
```
Note: this was the minimum to get the following to work, but there may be other parts of the build that are affected/unsupported (e.g., calling ```buildscripts\make_vcxproj.py```).

SCONS_HOME was set to the root of PR #4174. The scons invocation was:
```
python %SCONS_HOME%\scripts\scons.py install-mongod --disable-warnings-as-errors MSVC_VERSION=14.3 MSVC_TOOLSET_VERSION=14.2
```

The build was successful using toolset 14.29 but did report the following linker warnings (don't know if that's normal or not):
```
Linking build\opt\mongo\db\mongod.exe
   Creating library build\opt\mongo\db\mongod.lib and object build\opt\mongo\db\mongod.exp
LINK : warning LNK4217: symbol '?instance@MallocExtension@@SAPEAV1@XZ (public: static class MallocExtension * __cdecl MallocExtension::instance(void))' defined in 'tcmalloc_minimal.lib(malloc_extension.obj)' is imported by 'tcmalloc_set_parameter.lib(tcmalloc_set_parameter.obj)' in function '"public: virtual void __cdecl mongo::TCMallocReleaseRateServerParameter::append(class mongo::OperationContext *,class mongo::BSONObjBuilder &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?append@TCMallocReleaseRateServerParameter@mongo@@UEAAXPEAVOperationContext@2@AEAVBSONObjBuilder@2@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)'
LINK : warning LNK4286: symbol '?instance@MallocExtension@@SAPEAV1@XZ (public: static class MallocExtension * __cdecl MallocExtension::instance(void))' defined in 'tcmalloc_minimal.lib(malloc_extension.obj)' is imported by 'tcmalloc_set_parameter.lib(tcmalloc_server_status_section.obj)'
LINK : warning LNK4217: symbol 'tc_malloc' defined in 'tcmalloc_minimal.lib(tcmalloc.obj)' is imported by 'wiredtiger.lib(os_alloc.obj)' in function '__wt_malloc'
LINK : warning LNK4217: symbol 'tc_free' defined in 'tcmalloc_minimal.lib(tcmalloc.obj)' is imported by 'wiredtiger.lib(os_alloc.obj)' in function '__wt_free_int'
LINK : warning LNK4217: symbol 'tc_realloc' defined in 'tcmalloc_minimal.lib(tcmalloc.obj)' is imported by 'wiredtiger.lib(os_alloc.obj)' in function '__wt_realloc'
LINK : warning LNK4217: symbol 'tc_calloc' defined in 'tcmalloc_minimal.lib(tcmalloc.obj)' is imported by 'wiredtiger.lib(os_alloc.obj)' in function '__wt_calloc'
Install file: "build\opt\mongo\db\mongod.exe" as "build\install\bin\mongod.exe"
Install file: "build\opt\mongo\db\mongod.pdb" as "build\install\bin\mongod.pdb"
```

The SCons msvc cache was enabled and there was a single entry for the 14.29.30133 toolset of VS2022.

SCONS_MSCOMMON_DEBUG was enabled which yielded an issue with the logging implementation in MSCommon: the logging instance defined in MSCommon affected the root logger rather than being completely independent/isolated.  The fix was added to PR #4174.  This should be trivial to update in its own PR if desired.

At present, this is the best that can be done until MSVC_VERSION_TOOLSET is used during selection instead of after selection.  The probability of using MSVC_VERSION_TOOLSET for selection prior to the next release of SCons is effectively zero though.

Let me know if I there is anything patently absurd with the suggested kludge above.   Any and all feedback is appreciated.

**Comment by dmoody256** [comment]
Those warnings are expected.

I think what you said was in agreement with my comment. I never said 14.2 toolset with Visual Studio 2022 (14.3) will work without setting extra flags.

**Comment by bdbaddog** [comment]
Duplicate of #3664

**Comment by jcbrill** [comment]
> I think what you said was in agreement with my comment. I never said 14.2 toolset with Visual Studio 2022 (14.3) will work without setting extra flags.

I completely agree with your comment above.  I didn't mean to imply anything different.

I was interested in applying #4174 to something other than my in-house testing along the lines of "if one REALLY wanted to compile with the v142 toolset in VS2022" is it possible with the PR?

If nothing else, it shook out an issue with the logging which is useful.

There is a subtle difference between using the toolset for selection and applying it after selection.  I'm just trying to temper expectations of what can, and cannot, be achieved in #4174 until (someday) the toolset version is used for selection.

The main purpose of #4174 is to make all msvc batch file arguments available via SCons one way or another.  The current implementation of toolset version is analogous to the manner in which the msvc batch files work when configuring a msvc build from the command line: given the appropriate (vs2022) vcvars batch file, pass the (v142) toolset version as an argument.  

It's a start, but it won't be a solution in all situations.
